In [1]:
# CodeUp curriculum statistics exercises

In [2]:
# On a side note, I'm extremely excited to be learning statistics and using python/numpy to help with it! This is so cool what we are learning.

In [209]:
# First step is importing the libraries I'll need to use:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# I may not need the charting functions right away, but I prefer to have all my imports at the top of my file, per best practices cited by codeup instructors.

In [4]:
# First, starting out with examples from the curriculum for purposes of better rention of topic.

In [5]:
np.random.seed(29)

In [27]:
quartile_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.quantile(quartile_array, 0.25)

2.75

In [31]:
# np.random.choice?

In [32]:
# Example of flipping an unfair coin 10,000 times. "Unfair" as in the definition set in my probabilities variable.

probabilities = [.75, .25]
flips = np.random.choice(["Heads", "Tails"], size = 10_000, p=probabilities)
(flips == "Heads").mean()

0.753

In [38]:
mean_num = 50
std_dev_num = 25
numbers = np.random.normal(mean_num, std_dev_num, size = 10000)
numbers = pd.Series(numbers)


In [40]:
numbers.mean

<bound method Series.mean of 0       47.100626
1       49.127286
2       20.553275
3       58.104817
4       48.670140
          ...    
9995    64.030836
9996    57.717181
9997    70.174863
9998    72.704321
9999    33.394554
Length: 10000, dtype: float64>

In [23]:
# Now, on to the exercises for the Simulation lesson:

### 1. How likely is it that you roll doubles when rolling two dice?

In [64]:
# Setting up rolling the dice 10,000 times

# First I need to create a place (a variable) to store my die rolls (per die, since ultimately that's what I'm trying to compare):

die1 = np.random.choice([1, 2, 3, 4, 5, 6], size = 10_000)
die2 = np.random.choice([1, 2, 3, 4, 5, 6], size = 10_000)

In [58]:
# Now creating a boolean mask to return True or False depending on if the die rolls returns the same number.

die1 == die2

# And assigning that mask to a variable named doubles:
doubles = die1 == die2

In [59]:
# Nice little array I have of True/False observations.
doubles

array([False, False, False, ..., False, False,  True])

In [63]:
# Now find the sum / length, which is the average, ie, the CHANCE of the double number rolls:
# The quick way to do this is to use the .mean() function.

doubles.mean()

print(f'There is a {doubles.mean()} chance of the dice roll returning the same numbers.')

# Big thanks to Ryan for reminding me that since numpy uses arrays, I don't have to "manually" define a function that iterates through each observation. Numpy does that for me automatically. Cool!

There is a 0.1612 chance of the dice roll returning the same numbers.


### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [13]:
# So just like the prior problem, I need to setup variables to store the results for each coin I flip.
# coin1, coin2, etc.
# I'm only going to start with 100 coin tosses just to keep the numbers smaller for my understanding... then increase later.

coin1 = np.random.choice(["Heads", "Tails"], size = 100)
coin2 = np.random.choice(["Heads", "Tails"], size = 100)
coin3 = np.random.choice(["Heads", "Tails"], size = 100)
coin4 = np.random.choice(["Heads", "Tails"], size = 100)
coin5 = np.random.choice(["Heads", "Tails"], size = 100)
coin6 = np.random.choice(["Heads", "Tails"], size = 100)
coin7 = np.random.choice(["Heads", "Tails"], size = 100)
coin8 = np.random.choice(["Heads", "Tails"], size = 100)

In [14]:
# Visualizing what one of the coin toss result arrays looks like:

coin1

array(['Heads', 'Tails', 'Heads', 'Heads', 'Tails', 'Heads', 'Tails',
       'Heads', 'Heads', 'Heads', 'Tails', 'Heads', 'Tails', 'Heads',
       'Heads', 'Heads', 'Tails', 'Heads', 'Heads', 'Heads', 'Heads',
       'Tails', 'Tails', 'Tails', 'Heads', 'Heads', 'Tails', 'Heads',
       'Tails', 'Tails', 'Tails', 'Heads', 'Tails', 'Tails', 'Tails',
       'Tails', 'Tails', 'Heads', 'Heads', 'Tails', 'Tails', 'Heads',
       'Heads', 'Heads', 'Heads', 'Heads', 'Tails', 'Tails', 'Heads',
       'Tails', 'Heads', 'Heads', 'Tails', 'Tails', 'Tails', 'Heads',
       'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails',
       'Heads', 'Tails', 'Heads', 'Tails', 'Heads', 'Heads', 'Heads',
       'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails',
       'Tails', 'Heads', 'Tails', 'Heads', 'Heads', 'Tails', 'Heads',
       'Heads', 'Tails', 'Heads', 'Tails', 'Tails', 'Tails', 'Tails',
       'Tails', 'Heads', 'Heads', 'Tails', 'Heads', 'Tails', 'Tails',
       'Heads', 'Tai

In [15]:
# And for good measure confirming what the variable type is, which should be a numpy array:
type(coin1)

numpy.ndarray

In [16]:
# Now, in plain English, what I am trying to do is figure out a ratio which tells me how many times there were a set of flips in which 3 or fewer coins were showing heads.
# In other words, return True when 'Heads <= 3'


# test1 = lambda()... this is close but I need a full function. All the methods I tried with only lambda didn't work...

In [17]:
coin1[0] == coin2[0]

True

In [ ]:
# Thanks to fellow students, especially Sam on helping me through this one.

In [94]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? 
def heads_counter(coinflips):
    count = 0
    for result in coinflips:
        if result == 'heads':
            count += 1
    return count
n_sims = nrows = 10000
n_coins = ncols = 8
flips = np.random.choice(['heads', 'tails'], n_sims * n_coins).reshape(nrows, ncols)
flips_df = pd.DataFrame(flips)
flips_df.apply(lambda x: heads_counter(x) == 3, axis = 1).mean()

# Interestingly, when adding .mean() to the end of this last lamba apply it only counts the Trues, or 1s, in the resulting function result, but still averages it over the entire count of the rows. Boolean Masks are very powerful.

0.2142

In [5]:
# What is the probability of getting more than 3 heads?

def heads_counter(coinflips):
    count = 0
    for result in coinflips:
        if result == 'heads':
            count += 1
    return count
n_sims = nrows = 10000
n_coins = ncols = 8
flips = np.random.choice(['heads', 'tails'], n_sims * n_coins).reshape(nrows, ncols)
flips_df = pd.DataFrame(flips)
flips_df.apply(lambda x: heads_counter(x) > 3, axis = 1).mean()

0.6385

### 3. There are approximately 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [10]:
# Going to use the same function as before, since that seems to be working.

def billboard(student):
    count = 0
    for result in student:
        if result == 'ds':
            count += 1
    return count

n_sims2 = nrows = 10_000
n_students = ncols = 2

billboards = np.random.choice(['web1', 'web2', 'web3', 'ds'], n_sims2 * n_students).reshape(nrows, ncols)
billboards_df = pd.DataFrame(billboards)
billboards_df.apply(lambda x: billboard(x) > 1, axis = 1).mean()

# So, same concept as before, but this time the columns were only 2, since that's the number of "outputs" that we were trying to test on. Not 4, because we took care of that within the random choice function.

0.058

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [9]:
# Key on this one, don't return negative numbers... So I have to establish a baseline somewhere along in the function.

def pop_tarts(snack):
    count_snack = 0
    for x in snack:
        if result > 0:
            count_snack +=1
        return count_snack

In [18]:
n_sims3 = nrows = 10_000
n_vending = ncols = 1

In [39]:
# This doesn't work, I need to use another random number generator.

# vending_machine = np.random.randn()

In [41]:
# I think this is the right one to use, since we are talking about a normalized distribution.

# np.random.normal(loc = 4, scale = 1)

np.random.normal(3, 1.5, size = 10000)

array([ 3.52295482,  3.26860343,  3.40152975, ...,  6.52872321,
       -0.82321151,  1.80749872])

In [55]:
# But can't have a negative number in the distribution. 

numbers = np.random.normal(3, 1.5, size = (10000, 5))

positive_numbers = numbers > 0

positives = np.where(numbers < 0,0,numbers)
positives


0.7224

In [146]:
# Ryan's solution:

snacks_function = np.random.normal(3, 1.5, size=(100000, 5))

In [148]:
snacks_function[0]

array([3.77211756, 0.67312586, 4.04933388, 3.39314377, 3.50130476])

In [151]:
weekly_demand = snacks_function.sum(axis=1)

In [152]:
# Key step: Creating the boolean mask aka, the magic sauce.

weekly_demand < 17

array([ True,  True,  True, ...,  True,  True,  True])

In [153]:
(weekly_demand < 17).mean()

0.72699

In [54]:
# Trying to use list comprehension, but getting errors regarding the result being ambiguous. I think that's because of the nature of np arrays... I'm trying to iterate through an iteration == incorrect syntax.

# negatives = []

# for x in numbers:
#     if x < 0:
#         negatives += 1

# negative_nums = [n for n in numbers if n < 0]
    

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [58]:
# First, setup my random normal distributions. The question asks for two different distributions.

man_height = np.random.normal(178, 8, size = 10000)
woman_height = np.random.normal(170, 6, size = 10000)



In [59]:
# This is what one of the the arrays looks like.

man_height

array([181.17618618, 174.57230076, 181.08184378, ..., 190.23645622,
       166.18554029, 170.88289967])

In [62]:
# Now simply comparing the two arrays against each other gives me a boolean mask list...

man_height < woman_height

array([False, False, False, ..., False,  True,  True])

In [64]:
# And now I can simply use the same .mean() trick from earlier to only count the number of times the woman's height is higher than the man's, and then return that count divided by the total number of observations (rows) for an average chance.

(man_height < woman_height).mean()

# I definitely over-thought this one the first time through. Thanks for help on these...

0.2108

#### Ryan's Solutions:

In [162]:
trials_height = 100_000
m_heights = np.round(np.random.normal(178, 8, trials_height))
f_heights = np.round(np.random.normal(170, 6, trials_height))

In [163]:
type(f_heights)

numpy.ndarray

In [164]:
# Boolean Array
(m_heights < f_heights)

array([False, False, False, ..., False, False,  True])

In [167]:
# Chances of the woman being taller than the man.

(m_heights < f_heights).mean()

0.19734

In [168]:
# Finding the chance of the same height

(m_heights == f_heights).mean()

0.02917

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [9]:
# Using the same function/lambda combination.


anaconda = []

for x in range(0, 249):
    anaconda.append("not_corrupted " + str(x))
    
anaconda.append('Corrupted')

def corrupt_counter(downloads):
    count = 0
    for i in downloads:
        if i == 'Corrupted':
            count +=1
        return count

n_sims6 = nrows = 10000
n_downloads = ncols = 50

installs = np.random.choice(anaconda, n_sims6 * n_downloads).reshape(nrows, ncols)

installs_df = pd.DataFrame(installs)

installs_df.apply(lambda x: corrupt_counter(x) == 0, axis = 1).mean()

0.9961

In [10]:
# After 100 students have had installs:

anaconda100 = []

for x in range(0, 249):
    anaconda.append("not_corrupted " + str(x))
    
anaconda.append('Corrupted')

def corrupt_counter(downloads):
    count = 0
    for i in downloads:
        if i == 'Corrupted':
            count +=1
        return count

n_sims6 = nrows = 10000
n_downloads = ncols = 100

installs = np.random.choice(anaconda, n_sims6 * n_downloads).reshape(nrows, ncols)

installs_df = pd.DataFrame(installs)

installs_df.apply(lambda x: corrupt_counter(x) == 0, axis = 1).mean()

0.9955

In [12]:
# Chances for error within the first 150 student installs:

anaconda150 = []

for x in range(0, 249):
    anaconda.append("not_corrupted " + str(x))
    
anaconda.append('Corrupted')

def corrupt_counter(downloads):
    count = 0
    for i in downloads:
        if i == 'Corrupted':
            count +=1
        return count

n_sims6 = nrows = 10000
n_downloads = ncols = 150

installs = np.random.choice(anaconda, n_sims6 * n_downloads).reshape(nrows, ncols)

installs_df = pd.DataFrame(installs)

installs_df.apply(lambda x: corrupt_counter(x) == 0, axis = 1).mean()

0.9966

In [14]:
# How likely is it that 450 students all download anaconda without an issue?

anaconda450 = []

for x in range(0, 249):
    anaconda.append("not_corrupted " + str(x))
    
anaconda.append('Corrupted')

def corrupt_counter(downloads):
    count = 0
    for i in downloads:
        if i == 'Corrupted':
            count +=1
        return count

n_sims6 = nrows = 10000
n_downloads = ncols = 450

installs = np.random.choice(anaconda, n_sims6 * n_downloads).reshape(nrows, ncols)

installs_df = pd.DataFrame(installs)

installs_df.apply(lambda x: corrupt_counter(x) == 0, axis = 1).mean()

0.996

In [38]:
installs_df

0                  1                  2    \
0     not_corrupted 103  not_corrupted 147  not_corrupted 226   
1      not_corrupted 15  not_corrupted 177  not_corrupted 246   
2      not_corrupted 22   not_corrupted 89  not_corrupted 205   
3     not_corrupted 156  not_corrupted 241  not_corrupted 132   
4     not_corrupted 181    not_corrupted 5   not_corrupted 54   
...                 ...                ...                ...   
9995  not_corrupted 222  not_corrupted 113  not_corrupted 105   
9996   not_corrupted 50  not_corrupted 232   not_corrupted 72   
9997  not_corrupted 102   not_corrupted 50   not_corrupted 22   
9998  not_corrupted 192  not_corrupted 192   not_corrupted 12   
9999  not_corrupted 164  not_corrupted 240   not_corrupted 89   

                    3                  4                  5    \
0      not_corrupted 65  not_corrupted 188  not_corrupted 246   
1      not_corrupted 44   not_corrupted 69  not_corrupted 118   
2      not_corrupted 50  not_corrupted 186   not_corrupted 32   
3     not_corrupted 211  not_corrupted 200  not_corrupted 245   
4     not_corrupted 111  not_corrupted 150   not_corrupted 36   
...                 ...                ...                ...   
9995  not_corrupted 179  not_corrupted 178   not_corrupted 11   
9996   not_corrupted 50    not_corrupted 8  not_corrupted 227   
9997   not_corrupted 61   not_corrupted 62    not_corrupted 5   
9998  not_corrupted 121  not_corrupted 184   not_corrupted 15   
9999  not_corrupted 165   not_corrupted 34  not_corrupted 170   

                    6                  7                  8    \
0     not_corrupted 239  not_corrupted 139  not_corrupted 220   
1      not_corrupted 12   not_corrupted 14  not_corrupted 144   
2      not_corrupted 23  not_corrupted 211  not_corrupted 205   
3     not_corrupted 133  not_corrupted 189  not_corrupted 119   
4     not_corrupted 247  not_corrupted 108  not_corrupted 115   
...                 ...                ...                ...   
9995  not_corrupted 242  not_corrupted 193   not_corrupted 64   
9996  not_corrupted 206  not_corrupted 183  not_corrupted 207   
9997  not_corrupted 156   not_corrupted 37          Corrupted   
9998  not_corrupted 246   not_corrupted 29  not_corrupted 160   
9999   not_corrupted 35   not_corrupted 84   not_corrupted 64   

                    9    ...                440                441  \
0     not_corrupted 230  ...  not_corrupted 177   not_corrupted 50   
1      not_corrupted 44  ...   not_corrupted 17   not_corrupted 15   
2      not_corrupted 57  ...  not_corrupted 206  not_corrupted 226   
3     not_corrupted 151  ...   not_corrupted 14  not_corrupted 129   
4      not_corrupted 63  ...  not_corrupted 112  not_corrupted 132   
...                 ...  ...                ...                ...   
9995  not_corrupted 149  ...  not_corrupted 127  not_corrupted 245   
9996  not_corrupted 164  ...   not_corrupted 75  not_corrupted 106   
9997  not_corrupted 160  ...  not_corrupted 144  not_corrupted 120   
9998    not_corrupted 1  ...   not_corrupted 16  not_corrupted 180   
9999  not_corrupted 131  ...    not_corrupted 9  not_corrupted 212   

                    442                443                444  \
0      not_corrupted 32  not_corrupted 172  not_corrupted 170   
1     not_corrupted 129  not_corrupted 232  not_corrupted 170   
2      not_corrupted 75  not_corrupted 106   not_corrupted 22   
3     not_corrupted 193  not_corrupted 247   not_corrupted 64   
4      not_corrupted 47   not_corrupted 47   not_corrupted 67   
...                 ...                ...                ...   
9995  not_corrupted 112   not_corrupted 20   not_corrupted 41   
9996  not_corrupted 213  not_corrupted 217  not_corrupted 209   
9997  not_corrupted 231   not_corrupted 90  not_corrupted 129   
9998   not_corrupted 67  not_corrupted 203   not_corrupted 22   
9999   not_corrupted 74   not_corrupted 71   not_corrupted 63   

                    445                446             

#### Ryan's solutions:

In [170]:
install_trial = 100_000

In [174]:
students_per_trial = 50

installs_test = np.random.choice([0, 1], size = (install_trial, students_per_trial), p = [1/250, 249/250])

In [176]:
install_df = pd.DataFrame(installs_test)
install_df.head()

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
1   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
2   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
3   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
4   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

   47  48  49  
0   1   1   1  
1   1   1   1  
2   1   1   1  
3   1   1   1  
4   1   1   1  

[5 rows x 50 columns]

In [178]:
install_df["all_good"] = install_df.sum(axis = 1) == students_per_trial

# And the average:
install_df.all_good.mean()

0.81719

In [179]:
# Then repeat for all the other scenarios.

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [21]:
# This isn't the answer, but working out the syntax of the code.

probs = [.70, .30]

truck_chance = np.random.choice(["Present", "Away"], size = 10000, p = probs)
(truck_chance == "Present").mean()

0.6911

In [37]:
# Now I need to add in the chance that it hasn't shown up after 3 days out of 5...
# The above isn't right because I'm only finding the chance that the truck shows up on a given day, and not taking into account how many days are in the workweek. So need to retool.

present_chance = .7
days = ncols = 3
n_sim_rows = nrows = 10**5

# Ok, I had another student help me figure this part out. I couldn't get the random() to work until I added the extra set of parentheses. Why does that work? It hides the rows/columns and returns it as one argument for random()?

data_array = np.random.random((nrows, ncols))
appear_chance = data_array < present_chance
(appear_chance.sum(axis=1) == 0).mean()

0.02711

In [30]:
data_array

array([[0.89545879, 0.44517927, 0.19479911, ..., 0.22387665, 0.640841  ,
        0.27200044],
       [0.44777153, 0.01636965, 0.48456296, ..., 0.39218093, 0.11616882,
        0.3386555 ],
       [0.88153652, 0.53691076, 0.88935779, ..., 0.17611713, 0.24766465,
        0.04825953],
       ...,
       [0.67349743, 0.20167626, 0.74307501, ..., 0.05116797, 0.12640359,
        0.68859245],
       [0.03887204, 0.64069749, 0.8055885 , ..., 0.25820928, 0.95946585,
        0.91766687],
       [0.14059997, 0.53757202, 0.68445567, ..., 0.53696899, 0.88545506,
        0.74508631]])

#### Ryan's solution:

In [181]:
trucks_check = np.random.choice([1, 0], size = (100_000, 3), p = [.7, .3])

In [185]:
trucks_df_check = pd.DataFrame(trucks_check)
trucks_df_check.columns = ['day_1', 'day_2', 'day_3']

In [190]:
trucks_df_check["showed_up"] = trucks_df_check.sum(axis = 1)

In [191]:
trucks_df_check

day_1  day_2  day_3  showed_up
0          1      1      0          2
1          0      0      0          0
2          1      1      1          3
3          1      1      1          3
4          0      1      0          1
...      ...    ...    ...        ...
99995      1      1      1          3
99996      0      1      1          2
99997      0      1      0          1
99998      1      1      1          3
99999      1      1      1          3

[100000 rows x 4 columns]

In [193]:
(trucks_df_check.showed_up > 0).mean()

0.97195

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [117]:
# First, I'm going through the math so I understand the fundamentals of the problem.

# Number of people in the room:
total_people = 23
# Minimum number of people's bdays that have to match:
min_match = 2

# formula should be: (n * (n - 1)) / 2

possible_matches = (total_people * (total_people - 1)) / min_match

possible_matches

253.0

In [137]:
# Here is theoretical math I used to prove to myself that the birthday paradox was true:
birthday_paradox = round((364/365)**253, 4)

print(f'The percent chance of at least 2 people sharing a birthday in a room of 23 people is: {birthday_paradox:.2%}')

The percent chance of at least 2 people sharing a birthday in a room of 23 people is: 49.95%


In [119]:
# Initializing the birthdays that the function will iterate through...

birthdays = []

birthdays

[]

In [120]:
for x in range(0, 365):
    birthdays.append('day ' + str(x))

In [99]:
user_input_1st = int(input("How many people are in the room? "))

How many people are in the room? 23


In [206]:
# Defining the function:

def bday_count(x):
    if len(x) == len(set(x)):
        return False
    else:
        return True

# Using the same shape function to compare arrays:

n_sims8 = nrows = 10000
n_people = ncols = user_input_1st

bdays_count = np.random.choice(birthdays, n_sims8 * n_people).reshape(nrows, ncols)

bdays_df = pd.DataFrame(bdays_count)

result = bdays_df.apply(lambda x: bday_count(x) == True, axis = 1).mean()

print(f'The chance of at least two people sharing a birthday in a group of {n_people} people is {result:.2%}')

The chance of at least two people sharing a birthday in a group of 23 people is 51.10%


In [107]:
user_input_2nd = int(input("How many people are in the room? "))

How many people are in the room? 20


In [207]:
# Defining the function in a group of 20 people:

def bday_count(x):
    if len(x) == len(set(x)):
        return False
    else:
        return True

# Using the same shape function to compare arrays:

n_sims8 = nrows = 10000
n_people = ncols = 20

bdays_count = np.random.choice(birthdays, n_sims8 * n_people).reshape(nrows, ncols)

bdays_df = pd.DataFrame(bdays_count)

result = bdays_df.apply(lambda x: bday_count(x) == True, axis = 1).mean()

print(f'The chance of at least two people sharing a birthday in a group of {n_people} people is {result:.2%}')

The chance of at least two people sharing a birthday in a group of 20 people is 41.20%


In [109]:
user_input_3rd = int(input("How many people are in the room? "))

How many people are in the room? 40


In [208]:
# Defining the function in a group of 40 people:

def bday_count(x):
    if len(x) == len(set(x)):
        return False
    else:
        return True

# Using the same shape function to compare arrays:

n_sims8 = nrows = 10000
n_people = ncols = 40

bdays_count = np.random.choice(birthdays, n_sims8 * n_people).reshape(nrows, ncols)

bdays_df = pd.DataFrame(bdays_count)

result = bdays_df.apply(lambda x: bday_count(x) == True, axis = 1).mean()

print(f'The chance of at least two people sharing a birthday in a group of {n_people} people is {result:.2%}')

The chance of at least two people sharing a birthday in a group of 40 people is 89.86%


#### Ryan's solution:

In [194]:
n_simulations = 100_000
n_peeps = 23

birthdays_array = np.random.choice(range(365), size = (n_simulations, n_peeps))

In [195]:
birthdays_array

array([[ 36,   9, 176, ..., 148, 316, 216],
       [125, 138, 165, ...,  24,  20,  90],
       [184, 257,  37, ..., 178, 208, 231],
       ...,
       [ 16,  29, 296, ..., 298, 254, 172],
       [ 68, 225, 193, ..., 182, 258,   0],
       [ 45,  22, 317, ...,  10,  88, 281]])

In [196]:
num8_df = pd.DataFrame(birthdays_array)

In [197]:
num8_df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       36    9  176  178   24  124  279   33  241  157  ...  115  108  235   
1      125  138  165  323   78   73  218  114  343  298  ...  356  354  260   
2      184  257   37   93  243  343   35  214  243  328  ...  349  236   75   
3       10  171  279    8  332  215  341  131   88   41  ...  234   20  360   
4      296   18  256  338   37  339  310  262  137   18  ...  193  170   36   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  174    3   23  246  132  291  240  232   70  131  ...  182  105  174   
99996  308    4  303  171   83  354  212  341   47  105  ...   82   17  209   
99997   16   29  296    2  234   93  308  138  201  138  ...  356   52   58   
99998   68  225  193  278   26   87   38  315  328  215  ...   43  325  250   
99999   45   22  317  155  207  288    4   95   37  236  ...  304  295   59   

        16   17   18   19   20   21   22  
0      204  345  144  155  148  316  216  
1      128   57  315  134   24   20   90  
2      166  272  151  176  178  208  231  
3      343  311  163  327  264  130  173  
4      182  148  358  155  218    8  248  
...    ...  ...  ...  ...  ...  ...  ...  
99995   91  125   47  128   57  141   80  
99996  231  117  166  211  206  240   49  
99997  216  127  326   97  298  254  172  
99998  175  319  167  155  182  258    0  
99999    8  303  284  169   10   88  281  

[100000 rows x 23 columns]

In [199]:
num8_df["n_unique"] = num8_df.nunique(axis=1)
num8_df

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0       36    9  176  178   24  124  279   33  241  157  ...  108  235  204   
1      125  138  165  323   78   73  218  114  343  298  ...  354  260  128   
2      184  257   37   93  243  343   35  214  243  328  ...  236   75  166   
3       10  171  279    8  332  215  341  131   88   41  ...   20  360  343   
4      296   18  256  338   37  339  310  262  137   18  ...  170   36  182   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  174    3   23  246  132  291  240  232   70  131  ...  105  174   91   
99996  308    4  303  171   83  354  212  341   47  105  ...   17  209  231   
99997   16   29  296    2  234   93  308  138  201  138  ...   52   58  216   
99998   68  225  193  278   26   87   38  315  328  215  ...  325  250  175   
99999   45   22  317  155  207  288    4   95   37  236  ...  295   59    8   

        17   18   19   20   21   22  n_unique  
0      345  144  155  148  316  216        24  
1       57  315  134   24   20   90        24  
2      272  151  176  178  208  231        23  
3      311  163  327  264  130  173        24  
4      148  358  155  218    8  248        23  
...    ...  ...  ...  ...  ...  ...       ...  
99995  125   47  128   57  141   80        23  
99996  117  166  211  206  240   49        24  
99997  127  326   97  298  254  172        23  
99998  319  167  155  182  258    0        23  
99999  303  284  169   10   88  281        24  

[100000 rows x 24 columns]

In [201]:
(num8_df.n_unique != 23).mean()

0.62772